Test data endpoint
TheJacksonLaboratory/PhenopacketLab pull request #13
Opened 2022-03-14 17:11 UTC by ielis

Setup endpoints for real-world `Cohort`, `Family`, and `Phenopacket` instances.

2022-03-14 22:04 UTC, ielis commented
@belkassaby I added example `Phenopacket` endpoints to `api/v1/test/phenopacket/*`. The `Phenopacket`s are based on examples in [Phenopacket tools](https://github.com/phenopackets/phenopacket-tools/tree/main/phenotools-cli/src/main/java/org/phenopackets/phenotools/examples).

I'll add real-life examples of `Family` and `Cohort` tomorrow.

2022-03-16 16:50 UTC, belkassaby requested changes
I think we should return the endpoint response wrapped in a ResponseEntity. For the endpoints where things haven't been implemented, we put HttpStatus.NOT_IMPLEMENTED and for all the other ones where the result object is returned, HttpStatus.OK.

2022-03-16 16:50 UTC, belkassaby commented on phenopacketlab-restapi/src/main/java/org/monarchinitiative/phenopacketlab/restapi/controller/test/PhenopacketController.java
> +        return Examples.Phenopackets.acuteMyeloidLeukemia();
See ResponseEntity comment

2022-03-17 08:32 UTC, ielis commented
Hello @belkassaby, I wrapped the responses in `ResponseEntity` and set the appropriate `HttpStatus`.

2022-03-22 13:39 UTC, merged