Add interpretation UI with variant validator
TheJacksonLaboratory/PhenopacketLab pull request #133
Opened 2023-02-28 04:43 UTC by belkassaby

2023-03-08 17:52 UTC, ielis requested changes
Hi @belkassaby there is only one thing we need to resolve together before I can sign this off. Please see the comment regarding exception handling in `VariantValidatorFunctionalAnnotationService`.

2023-03-08 17:52 UTC, ielis commented on phenopacketlab-restapi/src/main/java/org/monarchinitiative/phenopacketlab/restapi/controller/FunctionalVariantAnnotationController.java
> +        if (transcript.equals("prefered")) {
`prefered` should be `preferred` (typo)

2023-03-08 17:52 UTC, ielis commented on phenopacketlab-io/src/main/java/org/monarchinitiative/phenopacketlab/io/VariantValidatorFunctionalAnnotationService.java
> +                            throw new Exception("Could not identify" + build + " in Variant Validator response.");
I am not sure this is the way how we should handle the exceptions. It sounds like an error to not get a response with the genome build we asked for, and I'm not sure the user can do anything about it. I think we should log an error, `continue`. Depending on whether we get at least one good item, we return something or an empty list. The empty list can indicate that something went wrong and that the frontend should display some generic message ("Sorry, something went wrong"). Alternatively, we should can add an exception to the `FunctionalVariantAnnotationService` API and handle it at the caller side. 

Please note that I changed the line 131.. such that the exception is logged and swallowed. The exception handling we're discussing here would need to include that case too.

@belkassaby what are your thoughts?

2023-03-08 18:46 UTC, belkassaby commented on phenopacketlab-core/src/main/java/org/monarchinitiative/phenopacketlab/core/ConceptConstantsServiceImpl.java
> +                                SubtreeNode modifierTreeConstants,
In the new endpoints I added to the backend (merged in dev now), tnm finding and disease stage, they also return SubTreeNodes, I think I might have put the Optional in there too. We need to make sure to refactor those the same way as the above

2023-03-08 18:47 UTC, belkassaby commented on phenopacketlab-restapi/pom.xml
> -        <!-- Swagger UI -->
We need spring doc and swagger core for the API documentation

2023-03-30 13:10 UTC, ielis commented on phenopacketlab-core/src/main/java/org/monarchinitiative/phenopacketlab/core/ConceptConstantsServiceConfigurer.java
> +    @Deprecated
Private methods are not subject to deprecation since they do not change the public API.

2023-03-30 17:04 UTC, iimpulse approved these changes

2023-03-30 17:04 UTC, iimpulse commented on frontend/src/app/component/pheno-creator/pheno-creator-routing.module.ts
> +                    { path: 'interpretations', component: InterpretationStepComponent },
This in here twice?

2023-04-02 02:55 UTC, merged