Sqa bug fixes
TheJacksonLaboratory/PhenopacketLab pull request #134
Opened 2023-03-03 13:30 UTC by belkassaby

This PR will fix #131, #127, #129, #116 and #132

2023-03-03 18:25 UTC, belkassaby commented
this branch has been deployed to http://35.227.26.28/

2023-03-08 16:02 UTC, ielis approved these changes
Looks good to me, thanks!

2023-03-08 16:04 UTC, merged

2023-03-08 16:59 UTC, iimpulse requested changes

2023-03-08 20:56 UTC, belkassaby commented on frontend/src/app/component/phenopacket/phenotypic-feature/phenotypic-feature.component.ts
> +            const result = [];
the result object which is an array is never re-assigned/re-initialized: it's initialized only once, right above. Then I call .push on the array object which doesn't re-assign the object. It's still the same object reference. If I was to later in the code do something like `code = ['new value', 'new valu2]; ` then yeah I should use let. I have a typescript linting which runs before each commit and throws errors if I was to re-initialize such a const variable. See [const/var/let](https://medium.com/javascript-scene/javascript-es6-var-let-or-const-ba58b8dcde75#:~:text=%60const%60%20is%20a%20signal%20that,always%20the%20entire%20containing%20function.) for more info.

2023-03-08 20:59 UTC, belkassaby commented on frontend/src/app/component/phenopacket/phenotypic-feature/phenotypic-feature.component.ts
> +            const result = [];
Also i didn't want to declare it at the class level, as it's used only in that bit of code to display a string of evidences separated by commas.

2023-03-08 21:00 UTC, belkassaby commented on frontend/src/app/component/shared/edit/disease-edit/disease-edit.component.ts
> +            console.log(laterality);
I'll remove these directly on the dev branch if it's ok.

2023-03-08 21:06 UTC, belkassaby commented on frontend/src/app/component/shared/edit/disease-edit/disease-edit.component.ts
> +            console.log(laterality);
actually I'll commit these in the current branch im working on.